### ISSUE TITLE
Sidebar Refactor

### ISSUE THREAD

**Issue by OCHIENGHerman** [edgarlevyings44/babyStore#7]
Checkout this improvements on sidebar <br>
![image](https://github.com/edgarlevyings44/babyStore/assets/58131746/b9667ab1-77b4-430a-8033-78d8fc9d1813) <br>
![image](https://github.com/edgarlevyings44/babyStore/assets/58131746/f8751cb4-6111-4a83-bb98-2841d0351453) <br>
![image](https://github.com/edgarlevyings44/babyStore/assets/58131746/fde66b52-f533-406c-8584-87bdf65c6081) <br>

**Comment by OCHIENGHerman** [comment]
Check feature branch for the changes

**Comment by edgarlevyings44** [comment]
This issue was fix by the commit below:
9a79b15df25a7d35fb5de65bd9367c884919e7e4
